services:
  server:
    build: ./server
    ports:
      - "9876:9876"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server/src:/app/src
      - ./data:/app/data

  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - server
    volumes:
      - ./client/src:/app/src
